modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="arlightchatclient"
version="${version}"
displayName="ArlightChat Client"
authors="Arlight"
description='''
Emotes, scoreboards, podios y cosméticos visuales de Pony0n, Somita y Bingo.
'''
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.arlightchatclient]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.arlightchatclient]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="CLIENT"
