package com.arlight.chatclient;
import net.minecraft.client.Minecraft;import net.minecraft.client.gui.GuiGraphics;import net.minecraft.client.gui.components.EditBox;import net.minecraft.client.gui.screens.Screen;import net.minecraft.network.chat.Component;import net.neoforged.neoforge.network.PacketDistributor;import java.util.*;
public final class PermissionsAdminScreen extends Screen {
 private EditBox search;private int categoryIndex=0,entryIndex=0,targetIndex=0;private boolean targetGroups=true;private int scroll=0;private static final int PINK=0xFFFF70C9,PURPLE=0xFF9A68FF,DARK=0xF0120F1B,CARD=0xE8241C32,MUTED=0xFFB8AFC4;
 public PermissionsAdminScreen(){super(Component.literal("Arlight Permissions"));}
 @Override protected void init(){search=new EditBox(font,width-310,24,210,20,Component.literal("Buscar jugador"));search.setHint(Component.literal("Jugador desconectado..."));addRenderableWidget(search);}
 @Override public void render(GuiGraphics g,int mx,int my,float pt){g.fill(0,0,width,height,0xB0080710);int x=18,y=16,w=width-36,h=height-32;g.fill(x,y,x+w,y+h,DARK);g.fill(x,y,x+5,y+h,PINK);g.drawString(font,"✦ ARLIGHT PERMISSIONS",x+20,y+12,0xFFFFFFFF,true);g.drawString(font,"LuckPerms • panel administrativo",x+20,y+27,MUTED,false);button(g,width-90,22,58,24,"Cerrar",mx,my,false);int navX=x+16,navY=y+55,navW=190;g.fill(navX,navY,navX+navW,y+h-16,0xA014101E);g.drawString(font,"CATEGORÍAS",navX+12,navY+10,PINK,true);List<PermissionsPanelState.Category> cats=PermissionsPanelState.categories();for(int i=0;i<cats.size();i++){int yy=navY+31+i*42;boolean sel=i==categoryIndex;g.fill(navX+7,yy,navX+navW-7,yy+35,sel?0xCC5A326F:CARD);var c=cats.get(i);g.drawString(font,c.icon()+"  "+c.name(),navX+16,yy+7,sel?0xFFFFFFFF:0xFFE8DEED,true);g.drawString(font,trim(c.description(),25),navX+16,yy+20,MUTED,false);}int bodyX=navX+navW+14,bodyW=w-navW-46;g.drawString(font,"DESTINO",bodyX,navY+2,0xFFFFFFFF,true);button(g,bodyX,navY+17,94,24,"Rangos",mx,my,targetGroups);button(g,bodyX+100,navY+17,104,24,"Jugadores",mx,my,!targetGroups);int listY=navY+50,targetW=205;g.fill(bodyX,listY,bodyX+targetW,y+h-16,0x9914101E);List<String> targets=targets();for(int i=0;i<Math.min(10,targets.size());i++){int idx=i+scroll;if(idx>=targets.size())break;int yy=listY+8+i*25;boolean sel=idx==targetIndex;g.fill(bodyX+6,yy,bodyX+targetW-6,yy+21,sel?0xCC623D77:0x55382A45);g.drawString(font,(targetGroups?"◆ ":"● ")+trim(targets.get(idx),22),bodyX+13,yy+6,sel?0xFFFFFFFF:MUTED,false);}if(!targetGroups){g.drawString(font,"Busca usuarios fuera de línea arriba",bodyX+8,y+h-30,MUTED,false);}int detailX=bodyX+targetW+14,detailW=bodyW-targetW-14;g.fill(detailX,listY,detailX+detailW,y+h-16,0x9914101E);if(!cats.isEmpty()){var cat=cats.get(Math.min(categoryIndex,cats.size()-1));g.drawString(font,cat.icon()+"  "+cat.name(),detailX+14,listY+12,PINK,true);g.drawString(font,trim(cat.description(),48),detailX+14,listY+28,MUTED,false);for(int i=0;i<cat.entries().size();i++){int yy=listY+50+i*48;if(yy+42>y+h-25)break;var e=cat.entries().get(i);boolean sel=i==entryIndex;g.fill(detailX+10,yy,detailX+detailW-10,yy+40,sel?0xCC4A315D:CARD);g.drawString(font,e.name(),detailX+20,yy+7,0xFFFFFFFF,true);g.drawString(font,trim(e.node(),38),detailX+20,yy+20,PURPLE,false);g.drawString(font,trim(e.description(),42),detailX+20,yy+30,MUTED,false);}int by=y+h-54;button(g,detailX+10,by,74,26,"Permitir",mx,my,false);button(g,detailX+90,by,62,26,"Negar",mx,my,false);button(g,detailX+158,by,70,26,"30 días",mx,my,false);button(g,detailX+234,by,58,26,"Limpiar",mx,my,false);}String toast=PermissionsPanelState.toast();if(!toast.isEmpty()){int tw=font.width(toast)+24;g.fill(width/2-tw/2,5,width/2+tw/2,21,PermissionsPanelState.toastError()?0xDD8C2536:0xDD286A45);g.drawCenteredString(font,toast,width/2,9,0xFFFFFFFF);}super.render(g,mx,my,pt);}
 private List<String> targets(){return targetGroups?PermissionsPanelState.groups():PermissionsPanelState.players().stream().map(PermissionsPanelState.OnlinePlayer::name).toList();}
 private void button(GuiGraphics g,int x,int y,int w,int h,String t,int mx,int my,boolean active){boolean over=mx>=x&&mx<x+w&&my>=y&&my<y+h;g.fill(x,y,x+w,y+h,active?0xDD7A3E91:(over?0xCC5F3A70:0xAA30243B));g.drawCenteredString(font,t,x+w/2,y+(h-8)/2,0xFFFFFFFF);}
 @Override public boolean mouseClicked(double mx,double my,int b){int x=18,y=16,w=width-36,h=height-32;if(mx>=width-90&&mx<width-32&&my>=22&&my<46){onClose();return true;}int navX=x+16,navY=y+55,navW=190;for(int i=0;i<PermissionsPanelState.categories().size();i++){int yy=navY+31+i*42;if(hit(mx,my,navX+7,yy,navW-14,35)){categoryIndex=i;entryIndex=0;return true;}}int bodyX=navX+navW+14;if(hit(mx,my,bodyX,navY+17,94,24)){targetGroups=true;targetIndex=0;return true;}if(hit(mx,my,bodyX+100,navY+17,104,24)){targetGroups=false;targetIndex=0;return true;}int listY=navY+50;List<String> ts=targets();for(int i=0;i<Math.min(10,ts.size());i++){if(hit(mx,my,bodyX+6,listY+8+i*25,193,21)){targetIndex=i+scroll;return true;}}int detailX=bodyX+219;var cats=PermissionsPanelState.categories();if(!cats.isEmpty()){var cat=cats.get(Math.min(categoryIndex,cats.size()-1));for(int i=0;i<cat.entries().size();i++){if(hit(mx,my,detailX+10,listY+50+i*48,width-detailX-38,40)){entryIndex=i;return true;}}int by=y+h-54;if(hit(mx,my,detailX+10,by,74,26)){apply("SET",true,0);return true;}if(hit(mx,my,detailX+90,by,62,26)){apply("SET",false,0);return true;}if(hit(mx,my,detailX+158,by,70,26)){apply("SET",true,2592000);return true;}if(hit(mx,my,detailX+234,by,58,26)){apply("CLEAR",true,0);return true;}}return super.mouseClicked(mx,my,b);}
 @Override public boolean keyPressed(int key,int scan,int mods){if(key==257&&search.isFocused()&&!search.getValue().isBlank()){send("SEARCH|"+PermissionsPanelState.enc(search.getValue()));return true;}return super.keyPressed(key,scan,mods);}
 private void apply(String op,boolean value,long seconds){var cats=PermissionsPanelState.categories();List<String> ts=targets();if(cats.isEmpty()||ts.isEmpty())return;var cat=cats.get(Math.min(categoryIndex,cats.size()-1));if(cat.entries().isEmpty())return;var e=cat.entries().get(Math.min(entryIndex,cat.entries().size()-1));String target=ts.get(Math.min(targetIndex,ts.size()-1));send("APPLY|"+PermissionsPanelState.enc(targetGroups?"group":"user")+"|"+PermissionsPanelState.enc(target)+"|"+PermissionsPanelState.enc(e.node())+"|"+op+"|"+value+"|"+seconds);}
 private static void send(String s){var mc=Minecraft.getInstance();if(mc.getConnection()!=null)mc.getConnection().send(new net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket(new PermissionsPanelPayload(s)));}
 private static boolean hit(double mx,double my,int x,int y,int w,int h){return mx>=x&&mx<x+w&&my>=y&&my<y+h;}private static String trim(String s,int n){return s.length()<=n?s:s.substring(0,Math.max(0,n-1))+"…";}
 @Override public void renderBackground(GuiGraphics g,int x,int y,float p){}@Override public boolean isPauseScreen(){return false;}
}
